name: my_site
description: My Flutter Portfolio application.
repository: https://gitlab.com/aliyazdi75/my_site
issue_tracker: https://gitlab.com/aliyazdi75/my_site/issues
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: any

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
  shared_preferences: '>=0.5.10 <2.0.0'
  url_launcher: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - fonts/google_fonts/
    - assets/images/avatar.jpg

  fonts:
    - family: MySiteIcons
      fonts:
        - asset: fonts/MySiteIcons.ttf
    - family: IRANSans-Medium
      fonts:
        - asset: fonts/IRANSans-Medium.ttf
    - family: IRANSans-Regular
      fonts:
        - asset: fonts/IRANSans-Regular.ttf
    - family: IRANSans-SemiBold
      fonts:
        - asset: fonts/IRANSans-SemiBold.ttf
    - family: IRANSans-Bold
      fonts:
        - asset: fonts/IRANSans-Bold.ttf
