name: my_site
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  intl_translation: any
  flutter_localized_locales: any

  cupertino_icons: ^0.1.3
  google_fonts: ^0.3.5
  shared_preferences: ^0.5.6+1
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  grinder: ^0.8.3+1

flutter:
  uses-material-design: true

  assets:
    - fonts/google_fonts/
    - assets/images/avatar.jpg

  fonts:
    - family: MySiteIcons
      fonts:
        - asset: fonts/MySiteIcons.ttf
