name: my_site
description: My Flutter Website.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  intl_translation: any
  flutter_localized_locales: any

  cupertino_icons: ^0.1.3
  google_fonts: ^0.3.9
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  grinder: ^0.8.3+1
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - fonts/google_fonts/
    - assets/images/avatar.jpg

  fonts:
    - family: MySiteIcons
      fonts:
        - asset: fonts/MySiteIcons.ttf
    - family: IRANSans-Medium
      fonts:
        - asset: fonts/IRANSans-Medium.ttf
    - family: IRANSans-Regular
      fonts:
        - asset: fonts/IRANSans-Regular.ttf
    - family: IRANSans-SemiBold
      fonts:
        - asset: fonts/IRANSans-SemiBold.ttf
    - family: IRANSans-Bold
      fonts:
        - asset: fonts/IRANSans-Bold.ttf
