name: aliyazdi75
version: 1.0.0
summary: A responsive Flutter portfolio application for any platforms
description: A responsive Flutter portfolio application for any platforms

confinement: strict
base: core18
grade: stable

apps:
  aliyazdi75:
    command: my_site
    extensions: [flutter-master]
    plugs:
      - network

parts:
  aliyazdi75:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
