name: Deploy to web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: master
      - run: flutter doctor -v

      # Checkout app code and get packages.
      - name: Checkout app code
        uses: actions/checkout@v2
      - run: flutter pub get

      # Build and deploy.
      - run: flutter build -v web --release
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public